import type { Exercise } from "./types";

// ~100 functional-fitness / CrossFit movements. Videos are intentionally left
// blank — the coach attaches a demo per movement with the in-app video picker
// (fabricating 100 YouTube links would just produce broken ones). The `variants`
// field drives the per-prescription implement/side selector in the builder.

const V_OLY = ["Barbell", "Double DB", "Single DB"];
const V_DB = ["Double DB", "Single DB"];
const V_KB = ["Single KB", "Double KB"];

export const CROSSFIT_EXERCISES: Exercise[] = [
  // ---- Olympic / barbell ----
  { id: "cf-squat-snatch", name: "Squat Snatch", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY },
  { id: "cf-power-snatch", name: "Power Snatch", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY },
  { id: "cf-hang-power-snatch", name: "Hang Power Snatch", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY },
  { id: "cf-hang-squat-snatch", name: "Hang Squat Snatch", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY },
  { id: "cf-squat-clean", name: "Squat Clean", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY },
  { id: "cf-hang-power-clean", name: "Hang Power Clean", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY },
  { id: "cf-hang-squat-clean", name: "Hang Squat Clean", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY },
  { id: "cf-clean-jerk", name: "Clean and Jerk", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY },
  { id: "cf-split-jerk", name: "Split Jerk", category: "Olympic", equipment: "Barbell", primaryMuscle: "Shoulders", variants: ["Barbell", "Double DB"] },
  { id: "cf-push-jerk", name: "Push Jerk", category: "Olympic", equipment: "Barbell", primaryMuscle: "Shoulders", variants: V_OLY },
  { id: "cf-push-press", name: "Push Press", category: "Push", equipment: "Barbell", primaryMuscle: "Shoulders", variants: V_OLY },
  { id: "cf-strict-press", name: "Strict Press", category: "Push", equipment: "Barbell", primaryMuscle: "Shoulders", variants: V_OLY },
  { id: "cf-snatch-balance", name: "Snatch Balance", category: "Olympic", equipment: "Barbell", primaryMuscle: "Shoulders / Legs" },
  { id: "cf-ohs", name: "Overhead Squat", category: "Olympic", equipment: "Barbell", primaryMuscle: "Quads / Core", variants: V_OLY },
  { id: "cf-snatch-grip-dl", name: "Snatch-Grip Deadlift", category: "Lower Body", equipment: "Barbell", primaryMuscle: "Posterior Chain" },
  { id: "cf-clean-pull", name: "Clean Pull", category: "Olympic", equipment: "Barbell", primaryMuscle: "Posterior Chain" },
  { id: "cf-snatch-pull", name: "Snatch Pull", category: "Olympic", equipment: "Barbell", primaryMuscle: "Posterior Chain" },
  { id: "cf-sdhp", name: "Sumo Deadlift High Pull", category: "Full Body", equipment: "Barbell", primaryMuscle: "Posterior Chain", variants: ["Barbell", "Single DB", "Single KB"] },
  { id: "cf-good-morning", name: "Good Morning", category: "Lower Body", equipment: "Barbell", primaryMuscle: "Hamstrings" },
  { id: "cf-sots-press", name: "Sots Press", category: "Olympic", equipment: "Barbell", primaryMuscle: "Shoulders" },
  { id: "cf-close-grip-bench", name: "Close-Grip Bench Press", category: "Push", equipment: "Barbell", primaryMuscle: "Triceps / Chest" },
  { id: "cf-floor-press", name: "Floor Press", category: "Push", equipment: "Barbell", primaryMuscle: "Chest", variants: V_OLY },
  { id: "cf-pendlay-row", name: "Pendlay Row", category: "Pull", equipment: "Barbell", primaryMuscle: "Back" },

  // ---- Dumbbell ----
  { id: "cf-db-snatch", name: "DB Snatch", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: ["Single DB"] },
  { id: "cf-db-thruster", name: "DB Thruster", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: V_DB },
  { id: "cf-db-hang-clean", name: "DB Hang Clean", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: V_DB },
  { id: "cf-db-power-clean", name: "DB Power Clean", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: V_DB },
  { id: "cf-db-clean-jerk", name: "DB Clean and Jerk", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: V_DB },
  { id: "cf-db-push-press", name: "DB Push Press", category: "Push", equipment: "Dumbbell", primaryMuscle: "Shoulders", variants: V_DB },
  { id: "cf-db-shoulder-oh", name: "DB Shoulder to Overhead", category: "Push", equipment: "Dumbbell", primaryMuscle: "Shoulders", variants: V_DB },
  { id: "cf-db-front-squat", name: "DB Front Squat", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads", variants: V_DB },
  { id: "cf-db-ohs", name: "DB Overhead Squat", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads / Core", variants: V_DB },
  { id: "cf-db-goblet-squat", name: "DB Goblet Squat", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads", variants: ["Single DB"] },
  { id: "cf-db-walking-lunge", name: "DB Walking Lunge", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads / Glutes", variants: V_DB },
  { id: "cf-db-reverse-lunge", name: "DB Reverse Lunge", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads / Glutes", variants: V_DB },
  { id: "cf-db-step-up", name: "DB Box Step-Up", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads / Glutes", variants: V_DB },
  { id: "cf-db-devils-press", name: "Devil's Press", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: ["Double DB"] },
  { id: "cf-db-man-maker", name: "Man Maker", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: ["Double DB"] },
  { id: "cf-db-renegade-row", name: "Renegade Row", category: "Pull", equipment: "Dumbbell", primaryMuscle: "Back / Core", variants: ["Double DB"] },
  { id: "cf-db-bent-row", name: "DB Bent-Over Row", category: "Pull", equipment: "Dumbbell", primaryMuscle: "Back", variants: ["Double DB", "Single arm"] },
  { id: "cf-db-floor-press", name: "DB Floor Press", category: "Push", equipment: "Dumbbell", primaryMuscle: "Chest", variants: V_DB },
  { id: "cf-db-bench", name: "DB Bench Press", category: "Push", equipment: "Dumbbell", primaryMuscle: "Chest", variants: V_DB },
  { id: "cf-db-hang-snatch", name: "DB Hang Snatch", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: ["Single DB"] },
  { id: "cf-db-front-rack-hold", name: "DB Front-Rack Hold", category: "Core", equipment: "Dumbbell", primaryMuscle: "Core", variants: V_DB },
  { id: "cf-farmers-carry", name: "Farmers Carry", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Grip / Core", variants: ["Double DB", "Single DB", "Double KB"] },
  { id: "cf-suitcase-carry", name: "Suitcase Carry", category: "Core", equipment: "Dumbbell", primaryMuscle: "Obliques / Grip", variants: ["Single DB", "Single KB"] },
  { id: "cf-db-russian-twist", name: "DB Russian Twist", category: "Core", equipment: "Dumbbell", primaryMuscle: "Obliques", variants: ["Single DB"] },

  // ---- Kettlebell ----
  { id: "cf-american-swing", name: "American KB Swing", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Posterior Chain" },
  { id: "cf-russian-swing", name: "Russian KB Swing", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Posterior Chain" },
  { id: "cf-kb-goblet-squat", name: "KB Goblet Squat", category: "Lower Body", equipment: "Kettlebell", primaryMuscle: "Quads" },
  { id: "cf-kb-clean", name: "KB Clean", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Full Body", variants: V_KB },
  { id: "cf-kb-snatch", name: "KB Snatch", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Full Body", variants: ["Single KB"] },
  { id: "cf-kb-press", name: "KB Strict Press", category: "Push", equipment: "Kettlebell", primaryMuscle: "Shoulders", variants: V_KB },
  { id: "cf-kb-push-press", name: "KB Push Press", category: "Push", equipment: "Kettlebell", primaryMuscle: "Shoulders", variants: V_KB },
  { id: "cf-kb-thruster", name: "KB Thruster", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Full Body", variants: V_KB },
  { id: "cf-kb-tgu", name: "Turkish Get-Up", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Full Body", variants: ["Single KB"] },
  { id: "cf-kb-front-lunge", name: "KB Front-Rack Lunge", category: "Lower Body", equipment: "Kettlebell", primaryMuscle: "Quads / Glutes", variants: V_KB },
  { id: "cf-kb-sumo-dl", name: "KB Sumo Deadlift", category: "Lower Body", equipment: "Kettlebell", primaryMuscle: "Posterior Chain" },
  { id: "cf-kb-windmill", name: "KB Windmill", category: "Core", equipment: "Kettlebell", primaryMuscle: "Obliques", variants: ["Single KB"] },
  { id: "cf-kb-high-pull", name: "KB High Pull", category: "Pull", equipment: "Kettlebell", primaryMuscle: "Back / Delts", variants: V_KB },

  // ---- Gymnastics ----
  { id: "cf-kipping-pullup", name: "Kipping Pull-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Lats / Back" },
  { id: "cf-ctb", name: "Chest-to-Bar Pull-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Lats / Back" },
  { id: "cf-butterfly-pullup", name: "Butterfly Pull-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Lats / Back" },
  { id: "cf-t2b", name: "Toes-to-Bar", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Core / Hip Flexors" },
  { id: "cf-k2e", name: "Knees-to-Elbow", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Core" },
  { id: "cf-bar-mu", name: "Bar Muscle-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Lats / Chest" },
  { id: "cf-ring-mu", name: "Ring Muscle-Up", category: "Gymnastics", equipment: "Rings", primaryMuscle: "Lats / Chest" },
  { id: "cf-ring-dip", name: "Ring Dip", category: "Gymnastics", equipment: "Rings", primaryMuscle: "Chest / Triceps" },
  { id: "cf-ring-row", name: "Ring Row", category: "Gymnastics", equipment: "Rings", primaryMuscle: "Back" },
  { id: "cf-ring-pushup", name: "Ring Push-Up", category: "Gymnastics", equipment: "Rings", primaryMuscle: "Chest" },
  { id: "cf-strict-hspu", name: "Strict Handstand Push-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Shoulders" },
  { id: "cf-kipping-hspu", name: "Kipping Handstand Push-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Shoulders" },
  { id: "cf-wall-walk", name: "Wall Walk", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Shoulders / Core" },
  { id: "cf-handstand-hold", name: "Handstand Hold", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Shoulders" },
  { id: "cf-handstand-walk", name: "Handstand Walk", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Shoulders" },
  { id: "cf-pistol", name: "Pistol Squat", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Quads", variants: ["Single leg"] },
  { id: "cf-air-squat", name: "Air Squat", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Quads" },
  { id: "cf-pushup", name: "Push-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Chest" },
  { id: "cf-hr-pushup", name: "Hand-Release Push-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Chest" },
  { id: "cf-box-jump", name: "Box Jump", category: "Gymnastics", equipment: "Box", primaryMuscle: "Legs" },
  { id: "cf-box-jump-over", name: "Box Jump Over", category: "Gymnastics", equipment: "Box", primaryMuscle: "Legs" },
  { id: "cf-box-step-up", name: "Box Step-Up", category: "Gymnastics", equipment: "Box", primaryMuscle: "Legs", variants: ["Bodyweight", "Double DB", "Single DB"] },
  { id: "cf-burpee-box-jump-over", name: "Burpee Box Jump Over", category: "Gymnastics", equipment: "Box", primaryMuscle: "Full Body" },
  { id: "cf-burpee-pullup", name: "Burpee Pull-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Full Body" },
  { id: "cf-rope-climb", name: "Rope Climb", category: "Gymnastics", equipment: "Other", primaryMuscle: "Back / Grip" },
  { id: "cf-ghd-situp", name: "GHD Sit-Up", category: "Core", equipment: "Machine", primaryMuscle: "Abs / Hip Flexors" },
  { id: "cf-abmat-situp", name: "AbMat Sit-Up", category: "Core", equipment: "Bodyweight", primaryMuscle: "Abs" },
  { id: "cf-vup", name: "V-Up", category: "Core", equipment: "Bodyweight", primaryMuscle: "Abs" },
  { id: "cf-hollow-rock", name: "Hollow Rock", category: "Core", equipment: "Bodyweight", primaryMuscle: "Abs" },
  { id: "cf-lsit", name: "L-Sit", category: "Core", equipment: "Bodyweight", primaryMuscle: "Abs / Hip Flexors" },
  { id: "cf-bear-crawl", name: "Bear Crawl", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Full Body" },

  // ---- Conditioning / monostructural / odd object ----
  { id: "cf-wall-ball", name: "Wall Ball", category: "Conditioning", equipment: "Medicine Ball", primaryMuscle: "Full Body" },
  { id: "cf-mb-clean", name: "Medicine Ball Clean", category: "Conditioning", equipment: "Medicine Ball", primaryMuscle: "Full Body" },
  { id: "cf-mb-slam", name: "Medicine Ball Slam", category: "Conditioning", equipment: "Medicine Ball", primaryMuscle: "Full Body" },
  { id: "cf-double-under", name: "Double Under", category: "Conditioning", equipment: "Jump Rope", primaryMuscle: "Calves / Heart" },
  { id: "cf-single-under", name: "Single Under", category: "Conditioning", equipment: "Jump Rope", primaryMuscle: "Calves / Heart" },
  { id: "cf-crossover", name: "Crossover (Jump Rope)", category: "Conditioning", equipment: "Jump Rope", primaryMuscle: "Calves / Coordination" },
  { id: "cf-ski-erg", name: "Ski Erg", category: "Conditioning", equipment: "Cardio Machine", primaryMuscle: "Full Body", activity: true, calories: true },
  { id: "cf-bike-erg", name: "Bike Erg", category: "Conditioning", equipment: "Cardio Machine", primaryMuscle: "Legs / Heart", activity: true, calories: true, speedUnit: "mph" },
  { id: "cf-echo-bike", name: "Echo Bike", category: "Conditioning", equipment: "Cardio Machine", primaryMuscle: "Full Body", activity: true, calories: true, speedUnit: "mph" },
  { id: "cf-row-cal", name: "Row (Calories)", category: "Conditioning", equipment: "Cardio Machine", primaryMuscle: "Full Body", activity: true, calories: true },
  { id: "cf-shuttle-run", name: "Shuttle Run", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Legs / Heart", activity: true },
  { id: "cf-sled-push", name: "Sled Push", category: "Conditioning", equipment: "Sled", primaryMuscle: "Legs / Full Body" },
  { id: "cf-sled-pull", name: "Sled Pull", category: "Conditioning", equipment: "Sled", primaryMuscle: "Back / Legs" },
  { id: "cf-sandbag-clean", name: "Sandbag Clean", category: "Conditioning", equipment: "Sandbag", primaryMuscle: "Full Body" },
  { id: "cf-sandbag-carry", name: "Sandbag Carry", category: "Conditioning", equipment: "Sandbag", primaryMuscle: "Full Body / Grip" },
  { id: "cf-sandbag-shoulder", name: "Sandbag Over Shoulder", category: "Conditioning", equipment: "Sandbag", primaryMuscle: "Full Body" },
  { id: "cf-sandbag-squat", name: "Sandbag Squat", category: "Lower Body", equipment: "Sandbag", primaryMuscle: "Quads / Full Body" },
  { id: "cf-bar-facing-burpee", name: "Bar-Facing Burpee", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Full Body" },
  { id: "cf-lateral-burpee", name: "Lateral Burpee Over Bar", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Full Body" },
  { id: "cf-broad-jump", name: "Broad Jump", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Legs" },
  { id: "cf-tuck-jump", name: "Tuck Jump", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Legs" },
  { id: "cf-jumping-lunge", name: "Jumping Lunge", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Legs", variants: ["Single leg"] },
  { id: "cf-mtn-climber", name: "Mountain Climber", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Core / Heart" },
  { id: "cf-inchworm", name: "Inchworm", category: "Mobility", equipment: "Bodyweight", primaryMuscle: "Full Body" },
  { id: "cf-single-leg-rdl", name: "Single-Leg RDL", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Hamstrings / Balance", variants: ["Single leg"] },
  { id: "cf-cossack-squat", name: "Cossack Squat", category: "Lower Body", equipment: "Bodyweight", primaryMuscle: "Adductors / Quads", variants: ["Single side"] },
  { id: "cf-nordic-curl", name: "Nordic Hamstring Curl", category: "Lower Body", equipment: "Bodyweight", primaryMuscle: "Hamstrings" },
  { id: "cf-glute-bridge", name: "Glute Bridge", category: "Lower Body", equipment: "Bodyweight", primaryMuscle: "Glutes" },
  { id: "cf-hip-extension", name: "GHD Hip Extension", category: "Lower Body", equipment: "Machine", primaryMuscle: "Posterior Chain" },
];
