import type { Exercise } from "./types";

// ~120 functional-fitness / CrossFit movements, each with a demo video
// (official CrossFit channel where available, else a reputable coaching
// channel; all URLs verified live via YouTube oEmbed 2026-07-11). Coaches can
// still swap a video per movement with the in-app video picker. The `variants`
// field drives the per-prescription implement/side selector in the builder.

const V_OLY = ["Barbell", "Double DB", "Single DB"];
const V_DB = ["Double DB", "Single DB"];
const V_KB = ["Single KB", "Double KB"];

export const CROSSFIT_EXERCISES: Exercise[] = [
  // ---- Olympic / barbell ----
  { id: "cf-squat-snatch", name: "Squat Snatch", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=GhxhiehJcQY" },
  { id: "cf-power-snatch", name: "Power Snatch", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=TL8SMp7RdXQ" },
  { id: "cf-hang-power-snatch", name: "Hang Power Snatch", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=-mLzQdVAwlw" },
  { id: "cf-hang-squat-snatch", name: "Hang Squat Snatch", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=IucshEToDyM" },
  { id: "cf-squat-clean", name: "Squat Clean", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=Ty14ogq_Vok" },
  { id: "cf-hang-power-clean", name: "Hang Power Clean", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=0aP3tgKZcHQ" },
  { id: "cf-hang-squat-clean", name: "Hang Squat Clean", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=DaKC_BEN5bk" },
  { id: "cf-clean-jerk", name: "Clean and Jerk", category: "Olympic", equipment: "Barbell", primaryMuscle: "Full Body", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=PjY1rH4_MOA" },
  { id: "cf-split-jerk", name: "Split Jerk", category: "Olympic", equipment: "Barbell", primaryMuscle: "Shoulders", variants: ["Barbell", "Double DB"], youtubeUrl: "https://www.youtube.com/watch?v=GUDkOtraHHY" },
  { id: "cf-push-jerk", name: "Push Jerk", category: "Olympic", equipment: "Barbell", primaryMuscle: "Shoulders", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=VrHNJXoSyXw" },
  { id: "cf-push-press", name: "Push Press", category: "Push", equipment: "Barbell", primaryMuscle: "Shoulders", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=iaBVSJm78ko" },
  { id: "cf-strict-press", name: "Strict Press", category: "Push", equipment: "Barbell", primaryMuscle: "Shoulders", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=5yWaNOvgFCM" },
  { id: "cf-snatch-balance", name: "Snatch Balance", category: "Olympic", equipment: "Barbell", primaryMuscle: "Shoulders / Legs", youtubeUrl: "https://www.youtube.com/watch?v=XuFaD1sAVGI" },
  { id: "cf-ohs", name: "Overhead Squat", category: "Olympic", equipment: "Barbell", primaryMuscle: "Quads / Core", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=pn8mqlG0nkE" },
  { id: "cf-snatch-grip-dl", name: "Snatch-Grip Deadlift", category: "Lower Body", equipment: "Barbell", primaryMuscle: "Posterior Chain", youtubeUrl: "https://www.youtube.com/watch?v=mp9gtX-JqB0" },
  { id: "cf-clean-pull", name: "Clean Pull", category: "Olympic", equipment: "Barbell", primaryMuscle: "Posterior Chain", youtubeUrl: "https://www.youtube.com/watch?v=xx8WkFrST2Y" },
  { id: "cf-snatch-pull", name: "Snatch Pull", category: "Olympic", equipment: "Barbell", primaryMuscle: "Posterior Chain", youtubeUrl: "https://www.youtube.com/watch?v=G1QygZ3Kd3w" },
  { id: "cf-sdhp", name: "Sumo Deadlift High Pull", category: "Full Body", equipment: "Barbell", primaryMuscle: "Posterior Chain", variants: ["Barbell", "Single DB", "Single KB"], youtubeUrl: "https://www.youtube.com/watch?v=gh55vVlwlQg" },
  { id: "cf-good-morning", name: "Good Morning", category: "Lower Body", equipment: "Barbell", primaryMuscle: "Hamstrings", youtubeUrl: "https://www.youtube.com/watch?v=YA-h3n9L4YU" },
  { id: "cf-sots-press", name: "Sots Press", category: "Olympic", equipment: "Barbell", primaryMuscle: "Shoulders", youtubeUrl: "https://www.youtube.com/watch?v=UrdNFJaTAnc" },
  { id: "cf-close-grip-bench", name: "Close-Grip Bench Press", category: "Push", equipment: "Barbell", primaryMuscle: "Triceps / Chest", youtubeUrl: "https://www.youtube.com/watch?v=vEUyEOVn3yM" },
  { id: "cf-floor-press", name: "Floor Press", category: "Push", equipment: "Barbell", primaryMuscle: "Chest", variants: V_OLY, youtubeUrl: "https://www.youtube.com/watch?v=6G-fNatzuSk" },
  { id: "cf-pendlay-row", name: "Pendlay Row", category: "Pull", equipment: "Barbell", primaryMuscle: "Back", youtubeUrl: "https://www.youtube.com/watch?v=f0Owf0svftU" },

  // ---- Dumbbell ----
  { id: "cf-db-snatch", name: "DB Snatch", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: ["Single DB"], youtubeUrl: "https://www.youtube.com/watch?v=R0mhHuVrLHA" },
  { id: "cf-db-thruster", name: "DB Thruster", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=u3wKkZjE8QM" },
  { id: "cf-db-hang-clean", name: "DB Hang Clean", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=8r44xv_Aqbw" },
  { id: "cf-db-power-clean", name: "DB Power Clean", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=viWI2rEt-HU" },
  { id: "cf-db-clean-jerk", name: "DB Clean and Jerk", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=olYaqKBXxb4" },
  { id: "cf-db-push-press", name: "DB Push Press", category: "Push", equipment: "Dumbbell", primaryMuscle: "Shoulders", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=4tCaD42ghlc" },
  { id: "cf-db-shoulder-oh", name: "DB Shoulder to Overhead", category: "Push", equipment: "Dumbbell", primaryMuscle: "Shoulders", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=AQ50ji32egc" },
  { id: "cf-db-front-squat", name: "DB Front Squat", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=B86Zj72LwzA" },
  { id: "cf-db-ohs", name: "DB Overhead Squat", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads / Core", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=azumEfnk-GI" },
  { id: "cf-db-goblet-squat", name: "DB Goblet Squat", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads", variants: ["Single DB"], youtubeUrl: "https://www.youtube.com/watch?v=pEGfGwp6IEA" },
  { id: "cf-db-walking-lunge", name: "DB Walking Lunge", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads / Glutes", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=wpYr3tVus3Q" },
  { id: "cf-db-reverse-lunge", name: "DB Reverse Lunge", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads / Glutes", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=Q2k3kYbtOcI" },
  { id: "cf-db-step-up", name: "DB Box Step-Up", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Quads / Glutes", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=5qjqDHOUh-A" },
  { id: "cf-db-devils-press", name: "Devil's Press", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: ["Double DB"], youtubeUrl: "https://www.youtube.com/watch?v=gaVoxC7RV_8" },
  { id: "cf-db-man-maker", name: "Man Maker", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: ["Double DB"], youtubeUrl: "https://www.youtube.com/watch?v=2-6EPLtSLwU" },
  { id: "cf-db-renegade-row", name: "Renegade Row", category: "Pull", equipment: "Dumbbell", primaryMuscle: "Back / Core", variants: ["Double DB"], youtubeUrl: "https://www.youtube.com/watch?v=PJpTBj4ilZw" },
  { id: "cf-db-bent-row", name: "DB Bent-Over Row", category: "Pull", equipment: "Dumbbell", primaryMuscle: "Back", variants: ["Double DB", "Single arm"], youtubeUrl: "https://www.youtube.com/watch?v=t7VDDNKBNx8" },
  { id: "cf-db-floor-press", name: "DB Floor Press", category: "Push", equipment: "Dumbbell", primaryMuscle: "Chest", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=tXv-rEa5xn8" },
  { id: "cf-db-bench", name: "DB Bench Press", category: "Push", equipment: "Dumbbell", primaryMuscle: "Chest", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=G9nf-QZeYWI" },
  { id: "cf-db-hang-snatch", name: "DB Hang Snatch", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Full Body", variants: ["Single DB"], youtubeUrl: "https://www.youtube.com/watch?v=BxoGj6GM_LU" },
  { id: "cf-db-front-rack-hold", name: "DB Front-Rack Hold", category: "Core", equipment: "Dumbbell", primaryMuscle: "Core", variants: V_DB, youtubeUrl: "https://www.youtube.com/watch?v=05syyiFOdao" },
  { id: "cf-farmers-carry", name: "Farmers Carry", category: "Full Body", equipment: "Dumbbell", primaryMuscle: "Grip / Core", variants: ["Double DB", "Single DB", "Double KB"], youtubeUrl: "https://www.youtube.com/watch?v=p5MNNosenJc" },
  { id: "cf-suitcase-carry", name: "Suitcase Carry", category: "Core", equipment: "Dumbbell", primaryMuscle: "Obliques / Grip", variants: ["Single DB", "Single KB"], youtubeUrl: "https://www.youtube.com/watch?v=UVAnha-hxW4" },
  { id: "cf-db-russian-twist", name: "DB Russian Twist", category: "Core", equipment: "Dumbbell", primaryMuscle: "Obliques", variants: ["Single DB"], youtubeUrl: "https://www.youtube.com/watch?v=O77eM1IkzS4" },

  // ---- Kettlebell ----
  { id: "cf-american-swing", name: "American KB Swing", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Posterior Chain", youtubeUrl: "https://www.youtube.com/watch?v=E6GoQYuZZT4" },
  { id: "cf-russian-swing", name: "Russian KB Swing", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Posterior Chain", youtubeUrl: "https://www.youtube.com/watch?v=uUpSFguwRQM" },
  { id: "cf-kb-goblet-squat", name: "KB Goblet Squat", category: "Lower Body", equipment: "Kettlebell", primaryMuscle: "Quads", youtubeUrl: "https://www.youtube.com/watch?v=qXzY3Bp2g7E" },
  { id: "cf-kb-clean", name: "KB Clean", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Full Body", variants: V_KB, youtubeUrl: "https://www.youtube.com/watch?v=cPYfiwpUeSE" },
  { id: "cf-kb-snatch", name: "KB Snatch", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Full Body", variants: ["Single KB"], youtubeUrl: "https://www.youtube.com/watch?v=ZQccQg4kDf8" },
  { id: "cf-kb-press", name: "KB Strict Press", category: "Push", equipment: "Kettlebell", primaryMuscle: "Shoulders", variants: V_KB, youtubeUrl: "https://www.youtube.com/watch?v=ihRozd9hafw" },
  { id: "cf-kb-push-press", name: "KB Push Press", category: "Push", equipment: "Kettlebell", primaryMuscle: "Shoulders", variants: V_KB, youtubeUrl: "https://www.youtube.com/watch?v=CCqru4q9RK0" },
  { id: "cf-kb-thruster", name: "KB Thruster", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Full Body", variants: V_KB, youtubeUrl: "https://www.youtube.com/watch?v=0-6iaZ-4-Cg" },
  { id: "cf-kb-tgu", name: "Turkish Get-Up", category: "Full Body", equipment: "Kettlebell", primaryMuscle: "Full Body", variants: ["Single KB"], youtubeUrl: "https://www.youtube.com/watch?v=-_zTytmHM94" },
  { id: "cf-kb-front-lunge", name: "KB Front-Rack Lunge", category: "Lower Body", equipment: "Kettlebell", primaryMuscle: "Quads / Glutes", variants: V_KB, youtubeUrl: "https://www.youtube.com/watch?v=gMb3N3kOYVk" },
  { id: "cf-kb-sumo-dl", name: "KB Sumo Deadlift", category: "Lower Body", equipment: "Kettlebell", primaryMuscle: "Posterior Chain", youtubeUrl: "https://www.youtube.com/watch?v=sGNMEtZCkRY" },
  { id: "cf-kb-windmill", name: "KB Windmill", category: "Core", equipment: "Kettlebell", primaryMuscle: "Obliques", variants: ["Single KB"], youtubeUrl: "https://www.youtube.com/watch?v=ITSmgn_BQgY" },
  { id: "cf-kb-high-pull", name: "KB High Pull", category: "Pull", equipment: "Kettlebell", primaryMuscle: "Back / Delts", variants: V_KB, youtubeUrl: "https://www.youtube.com/watch?v=o6QniJ9FaGA" },

  // ---- Gymnastics ----
  { id: "cf-kipping-pullup", name: "Kipping Pull-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Lats / Back", youtubeUrl: "https://www.youtube.com/watch?v=r45xLlH7r_M" },
  { id: "cf-ctb", name: "Chest-to-Bar Pull-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Lats / Back", youtubeUrl: "https://www.youtube.com/watch?v=AyPTCEXTjOo" },
  { id: "cf-butterfly-pullup", name: "Butterfly Pull-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Lats / Back", youtubeUrl: "https://www.youtube.com/watch?v=OenVG15QMj8" },
  { id: "cf-t2b", name: "Toes-to-Bar", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Core / Hip Flexors", youtubeUrl: "https://www.youtube.com/watch?v=_03pCKOv4l4" },
  { id: "cf-k2e", name: "Knees-to-Elbow", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Core", youtubeUrl: "https://www.youtube.com/watch?v=7Atq34fA1eU" },
  { id: "cf-bar-mu", name: "Bar Muscle-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Lats / Chest", youtubeUrl: "https://www.youtube.com/watch?v=iUAukdE0QQ4" },
  { id: "cf-ring-mu", name: "Ring Muscle-Up", category: "Gymnastics", equipment: "Rings", primaryMuscle: "Lats / Chest", youtubeUrl: "https://www.youtube.com/watch?v=G8W0BhzrWcs" },
  { id: "cf-ring-dip", name: "Ring Dip", category: "Gymnastics", equipment: "Rings", primaryMuscle: "Chest / Triceps", youtubeUrl: "https://www.youtube.com/watch?v=Vt0lO4jpIDo" },
  { id: "cf-ring-row", name: "Ring Row", category: "Gymnastics", equipment: "Rings", primaryMuscle: "Back", youtubeUrl: "https://www.youtube.com/watch?v=xhlReCpAE9k" },
  { id: "cf-ring-pushup", name: "Ring Push-Up", category: "Gymnastics", equipment: "Rings", primaryMuscle: "Chest", youtubeUrl: "https://www.youtube.com/watch?v=FRiiZRhapeU" },
  { id: "cf-strict-hspu", name: "Strict Handstand Push-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Shoulders", youtubeUrl: "https://www.youtube.com/watch?v=hvoQiF0kBI8" },
  { id: "cf-kipping-hspu", name: "Kipping Handstand Push-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Shoulders", youtubeUrl: "https://www.youtube.com/watch?v=InRvHNUOlSs" },
  { id: "cf-wall-walk", name: "Wall Walk", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Shoulders / Core", youtubeUrl: "https://www.youtube.com/watch?v=2TnX8j29tRY" },
  { id: "cf-handstand-hold", name: "Handstand Hold", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Shoulders", youtubeUrl: "https://www.youtube.com/watch?v=8Fdyew622mg" },
  { id: "cf-handstand-walk", name: "Handstand Walk", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Shoulders", youtubeUrl: "https://www.youtube.com/watch?v=I5p2VVDupq8" },
  { id: "cf-pistol", name: "Pistol Squat", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Quads", variants: ["Single leg"], youtubeUrl: "https://www.youtube.com/watch?v=qDcniqddTeE" },
  { id: "cf-air-squat", name: "Air Squat", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Quads", youtubeUrl: "https://www.youtube.com/watch?v=C_VtOYc6j5c" },
  { id: "cf-pushup", name: "Push-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Chest", youtubeUrl: "https://www.youtube.com/watch?v=0pkjOk0EiAk" },
  { id: "cf-hr-pushup", name: "Hand-Release Push-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Chest", youtubeUrl: "https://www.youtube.com/watch?v=TZSgRu7-sCk" },
  { id: "cf-box-jump", name: "Box Jump", category: "Gymnastics", equipment: "Box", primaryMuscle: "Legs", youtubeUrl: "https://www.youtube.com/watch?v=52r_Ul5k03g" },
  { id: "cf-box-jump-over", name: "Box Jump Over", category: "Gymnastics", equipment: "Box", primaryMuscle: "Legs", youtubeUrl: "https://www.youtube.com/watch?v=4o2duvMXo1Y" },
  { id: "cf-box-step-up", name: "Box Step-Up", category: "Gymnastics", equipment: "Box", primaryMuscle: "Legs", variants: ["Bodyweight", "Double DB", "Single DB"], youtubeUrl: "https://www.youtube.com/watch?v=5qjqDHOUh-A" },
  { id: "cf-burpee-box-jump-over", name: "Burpee Box Jump Over", category: "Gymnastics", equipment: "Box", primaryMuscle: "Full Body", youtubeUrl: "https://www.youtube.com/watch?v=GLktGkmcvWE" },
  { id: "cf-burpee-pullup", name: "Burpee Pull-Up", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Full Body", youtubeUrl: "https://www.youtube.com/watch?v=WVyFdjd96rM" },
  { id: "cf-rope-climb", name: "Rope Climb", category: "Gymnastics", equipment: "Other", primaryMuscle: "Back / Grip", youtubeUrl: "https://www.youtube.com/watch?v=zBoTgBpkn7o" },
  { id: "cf-ghd-situp", name: "GHD Sit-Up", category: "Core", equipment: "Machine", primaryMuscle: "Abs / Hip Flexors", youtubeUrl: "https://www.youtube.com/watch?v=1pbZ8mX2D1U" },
  { id: "cf-abmat-situp", name: "AbMat Sit-Up", category: "Core", equipment: "Bodyweight", primaryMuscle: "Abs", youtubeUrl: "https://www.youtube.com/watch?v=VIZX2Ru9qU8" },
  { id: "cf-vup", name: "V-Up", category: "Core", equipment: "Bodyweight", primaryMuscle: "Abs", youtubeUrl: "https://www.youtube.com/watch?v=Mk4zCq9b6hU" },
  { id: "cf-hollow-rock", name: "Hollow Rock", category: "Core", equipment: "Bodyweight", primaryMuscle: "Abs", youtubeUrl: "https://www.youtube.com/watch?v=p7j02V1fIzU" },
  { id: "cf-lsit", name: "L-Sit", category: "Core", equipment: "Bodyweight", primaryMuscle: "Abs / Hip Flexors", youtubeUrl: "https://www.youtube.com/watch?v=_HbccxgnCg0" },
  { id: "cf-bear-crawl", name: "Bear Crawl", category: "Gymnastics", equipment: "Bodyweight", primaryMuscle: "Full Body", youtubeUrl: "https://www.youtube.com/watch?v=-JcD5SOqW50" },

  // ---- Conditioning / monostructural / odd object ----
  { id: "cf-wall-ball", name: "Wall Ball", category: "Conditioning", equipment: "Medicine Ball", primaryMuscle: "Full Body", youtubeUrl: "https://www.youtube.com/watch?v=EqjGKsiIMCE" },
  { id: "cf-mb-clean", name: "Medicine Ball Clean", category: "Conditioning", equipment: "Medicine Ball", primaryMuscle: "Full Body", youtubeUrl: "https://www.youtube.com/watch?v=-nk0GqeSTJs" },
  { id: "cf-mb-slam", name: "Medicine Ball Slam", category: "Conditioning", equipment: "Medicine Ball", primaryMuscle: "Full Body", youtubeUrl: "https://www.youtube.com/watch?v=ePo39a3mSfk" },
  { id: "cf-double-under", name: "Double Under", category: "Conditioning", equipment: "Jump Rope", primaryMuscle: "Calves / Heart", youtubeUrl: "https://www.youtube.com/watch?v=-tF3hUsPZAI" },
  { id: "cf-single-under", name: "Single Under", category: "Conditioning", equipment: "Jump Rope", primaryMuscle: "Calves / Heart", youtubeUrl: "https://www.youtube.com/watch?v=k1JaZBz8VeQ" },
  { id: "cf-crossover", name: "Crossover (Jump Rope)", category: "Conditioning", equipment: "Jump Rope", primaryMuscle: "Calves / Coordination", youtubeUrl: "https://www.youtube.com/watch?v=EmgwMdrqQwI" },
  { id: "cf-ski-erg", name: "Ski Erg", category: "Conditioning", equipment: "Cardio Machine", primaryMuscle: "Full Body", activity: true, calories: true, youtubeUrl: "https://www.youtube.com/watch?v=B0lIgT5PHc8" },
  { id: "cf-bike-erg", name: "Bike Erg", category: "Conditioning", equipment: "Cardio Machine", primaryMuscle: "Legs / Heart", activity: true, calories: true, speedUnit: "mph", youtubeUrl: "https://www.youtube.com/watch?v=NS6pUSl4lYg" },
  { id: "cf-echo-bike", name: "Echo Bike", category: "Conditioning", equipment: "Cardio Machine", primaryMuscle: "Full Body", activity: true, calories: true, speedUnit: "mph", youtubeUrl: "https://www.youtube.com/watch?v=Z9omn9k8k5Q" },
  { id: "cf-row-cal", name: "Row (Calories)", category: "Conditioning", equipment: "Cardio Machine", primaryMuscle: "Full Body", activity: true, calories: true, youtubeUrl: "https://www.youtube.com/watch?v=QPvYrfyGHi8" },
  { id: "cf-shuttle-run", name: "Shuttle Run", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Legs / Heart", activity: true, youtubeUrl: "https://www.youtube.com/watch?v=EIJ6v6FXwVI" },
  { id: "cf-sled-push", name: "Sled Push", category: "Conditioning", equipment: "Sled", primaryMuscle: "Legs / Full Body", youtubeUrl: "https://www.youtube.com/watch?v=9XRRXaUpnLk" },
  { id: "cf-sled-pull", name: "Sled Pull", category: "Conditioning", equipment: "Sled", primaryMuscle: "Back / Legs", youtubeUrl: "https://www.youtube.com/watch?v=t081dogLJsU" },
  { id: "cf-sandbag-clean", name: "Sandbag Clean", category: "Conditioning", equipment: "Sandbag", primaryMuscle: "Full Body", youtubeUrl: "https://www.youtube.com/watch?v=dHJhVwwP--M" },
  { id: "cf-sandbag-carry", name: "Sandbag Carry", category: "Conditioning", equipment: "Sandbag", primaryMuscle: "Full Body / Grip", youtubeUrl: "https://www.youtube.com/watch?v=rxCHqGoX-bg" },
  { id: "cf-sandbag-shoulder", name: "Sandbag Over Shoulder", category: "Conditioning", equipment: "Sandbag", primaryMuscle: "Full Body", youtubeUrl: "https://www.youtube.com/watch?v=2pnxTZKlYoU" },
  { id: "cf-sandbag-squat", name: "Sandbag Squat", category: "Lower Body", equipment: "Sandbag", primaryMuscle: "Quads / Full Body", youtubeUrl: "https://www.youtube.com/watch?v=oT_Nin52nJk" },
  { id: "cf-bar-facing-burpee", name: "Bar-Facing Burpee", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Full Body", youtubeUrl: "https://www.youtube.com/watch?v=wcA_-ciyjsY" },
  { id: "cf-lateral-burpee", name: "Lateral Burpee Over Bar", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Full Body", youtubeUrl: "https://www.youtube.com/watch?v=Kv5goMENSsI" },
  { id: "cf-broad-jump", name: "Broad Jump", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Legs", youtubeUrl: "https://www.youtube.com/watch?v=AOkmLTD8J24" },
  { id: "cf-tuck-jump", name: "Tuck Jump", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Legs", youtubeUrl: "https://www.youtube.com/watch?v=jNuaFm7Z2Ns" },
  { id: "cf-jumping-lunge", name: "Jumping Lunge", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Legs", variants: ["Single leg"], youtubeUrl: "https://www.youtube.com/watch?v=6SFgE2_og_s" },
  { id: "cf-mtn-climber", name: "Mountain Climber", category: "Conditioning", equipment: "Bodyweight", primaryMuscle: "Core / Heart", youtubeUrl: "https://www.youtube.com/watch?v=A1hg_fqrPks" },
  { id: "cf-inchworm", name: "Inchworm", category: "Mobility", equipment: "Bodyweight", primaryMuscle: "Full Body", youtubeUrl: "https://www.youtube.com/watch?v=Hx1UsDQxT4M" },
  { id: "cf-single-leg-rdl", name: "Single-Leg RDL", category: "Lower Body", equipment: "Dumbbell", primaryMuscle: "Hamstrings / Balance", variants: ["Single leg"], youtubeUrl: "https://www.youtube.com/watch?v=ljsjrnw0-3A" },
  { id: "cf-cossack-squat", name: "Cossack Squat", category: "Lower Body", equipment: "Bodyweight", primaryMuscle: "Adductors / Quads", variants: ["Single side"], youtubeUrl: "https://www.youtube.com/watch?v=Qn5r1xZkC5Q" },
  { id: "cf-nordic-curl", name: "Nordic Hamstring Curl", category: "Lower Body", equipment: "Bodyweight", primaryMuscle: "Hamstrings", youtubeUrl: "https://www.youtube.com/watch?v=_e9vFU9-tkc" },
  { id: "cf-glute-bridge", name: "Glute Bridge", category: "Lower Body", equipment: "Bodyweight", primaryMuscle: "Glutes", youtubeUrl: "https://www.youtube.com/watch?v=tl6xvm4-Qk0" },
  { id: "cf-hip-extension", name: "GHD Hip Extension", category: "Lower Body", equipment: "Machine", primaryMuscle: "Posterior Chain", youtubeUrl: "https://www.youtube.com/watch?v=7X075Hrl5lE" },
];
