// AUTO-GENERATED by scripts/gen-releases.mjs — do not edit by hand.
// Regenerated at build time from recent git commit subjects.
export const buildDate = "2026-06-27";
export const commits: { sha: string; subject: string }[] = [
  {
    "sha": "f4491e1",
    "subject": "timer count-in, skip final rest, halfway voice, 3-2-1 ticks, finish confetti"
  },
  {
    "sha": "84d0dc4",
    "subject": "Per-set logging: weight + reps per set, for prescribed and athlete-added work"
  },
  {
    "sha": "2536506",
    "subject": "Auto-generated 'what's new' popup on new deploys"
  },
  {
    "sha": "0837fd1",
    "subject": "default Add-programming modal to Single session, tabs Single | Multi-week"
  },
  {
    "sha": "69c2500",
    "subject": "consolidated program entry points + scoped program management"
  },
  {
    "sha": "78647c9",
    "subject": "demo first screen blank on /demo reload until a tab is clicked"
  },
  {
    "sha": "dd0d183",
    "subject": "program tooling in main app — 8 presets, custom plans, movement swap"
  },
  {
    "sha": "7d8b1b9",
    "subject": "Demo: coach-built custom multi-week plans + calendar start date (v71)"
  },
  {
    "sha": "5c1f7e3",
    "subject": "Demo: multi-week program templates applied to athletes (v70)"
  },
  {
    "sha": "2667f17",
    "subject": "Demo: grade badge text adaptive (light on off-black) (v69)"
  },
  {
    "sha": "e539b20",
    "subject": "Demo: kill lime green (gold for & gold schools), clean swatches, mono Revere (v68)"
  },
  {
    "sha": "c6ca77f",
    "subject": "Demo: Norton Panthers emoji back to paws 🐾 (v67)"
  },
  {
    "sha": "8d9b962",
    "subject": "Demo: gold accent for & gold schools, mascot greeting, ring + emoji polish (v66)"
  },
  {
    "sha": "30b2916",
    "subject": "Demo: smart Program copy + cleaner off-black (v65)"
  },
  {
    "sha": "62d4b4c",
    "subject": "Demo: hue-preserving brand brightening + scoreboard back-nav (v64)"
  },
  {
    "sha": "cefc9f5",
    "subject": "Demo: clickable scoreboard rows+dates, cairn/high-bar icons, copy + form polish (v63)"
  },
  {
    "sha": "ffd2358",
    "subject": "Demo: varied lift profiles (one freak) + dark-mode brand text legibility (v62)"
  },
  {
    "sha": "c5a5490",
    "subject": "Demo: manual bulk programming + clearer Program entry + collapsible filter (v61)"
  },
  {
    "sha": "26729d0",
    "subject": "Demo: local workout gen (fix bulk 401), true floating nav, scaled maxes (v60)"
  },
  {
    "sha": "57d6933",
    "subject": "Demo: fix broken brand picker + floating nav, units, filter polish (v59)"
  },
  {
    "sha": "db90caa",
    "subject": "Demo: positions + grade, roster/scoreboard filter, bulk program; polish (v58)"
  },
  {
    "sha": "e63ee95",
    "subject": "Demo: sticky control bar + crisp category icons (v57)"
  },
  {
    "sha": "f5ebda3",
    "subject": "Demo: team scoreboard + control cluster, athlete labels, installable /demo (v56)"
  },
  {
    "sha": "eddbaae",
    "subject": "Demo: per-program backdrop toggle (cream / off-white / off-black), v55"
  },
  {
    "sha": "a7c8c4a",
    "subject": "Add Cloverleaf + 8 more area schools to white-label demo (17 total), v54"
  },
  {
    "sha": "18cf4ff",
    "subject": "Demo: stronger master password, bump v53 for production ship"
  },
  {
    "sha": "51fbfbe",
    "subject": "White-label demo: school skinner + master demo login"
  },
  {
    "sha": "1530da9",
    "subject": "Move weekly goal ring into the header; v52"
  },
  {
    "sha": "f7c42df",
    "subject": "Fill greeting dead space with a today's-date badge; v51"
  },
  {
    "sha": "c6bc07c",
    "subject": "Fix Build-a-workout coach toggle rendering; v50"
  }
];
