// Trace the real BUILD logomark (public/logo-icon.png) into exact SVG paths so
// the brand mark + launch splash use the ACTUAL artwork, not a hand-drawn
// approximation. Emits src/components/markPaths.ts.
//
//   B_SOLID_PATH    – the filled B silhouette (kettlebell area filled in, no holes)
//   KETTLEBELL_PATH – the kettlebell: interior bone region with its grip left as
//                     a hole (potrace winds holes opposite → render with default
//                     nonzero fill, NOT evenodd)
//   MARK_W / MARK_H – tight viewBox dimensions
//   KB_PIVOT        – pendulum pivot (the handle/grip), in viewBox coords
//
// The final mark = B_SOLID filled forest, with KETTLEBELL masked out.

import sharp from "sharp";
import potrace from "potrace";
import { writeFileSync } from "node:fs";

const SRC = "public/logo-icon.png";

const { data, info } = await sharp(SRC).removeAlpha().raw().toBuffer({ resolveWithObject: true });
const W = info.width;
const H = info.height;
const ch = info.channels; // 3

// forest = dark pixel, bone = light pixel
const isForest = new Uint8Array(W * H);
for (let i = 0; i < W * H; i++) {
  const r = data[i * ch];
  const g = data[i * ch + 1];
  const b = data[i * ch + 2];
  const lum = 0.3 * r + 0.59 * g + 0.11 * b;
  isForest[i] = lum < 130 ? 1 : 0;
}

// flood-fill the exterior bone from every border pixel (over non-forest pixels)
const exterior = new Uint8Array(W * H);
const stack = [];
const pushIf = (x, y) => {
  if (x < 0 || y < 0 || x >= W || y >= H) return;
  const i = y * W + x;
  if (exterior[i] || isForest[i]) return;
  exterior[i] = 1;
  stack.push(i);
};
for (let x = 0; x < W; x++) {
  pushIf(x, 0);
  pushIf(x, H - 1);
}
for (let y = 0; y < H; y++) {
  pushIf(0, y);
  pushIf(W - 1, y);
}
while (stack.length) {
  const i = stack.pop();
  const x = i % W;
  const y = (i / W) | 0;
  pushIf(x + 1, y);
  pushIf(x - 1, y);
  pushIf(x, y + 1);
  pushIf(x, y - 1);
}

// region predicates
const bSolid = (i) => (exterior[i] ? 0 : 1); // everything inside the B outer edge
const kettlebell = (i) => (!exterior[i] && !isForest[i] ? 1 : 0); // interior bone

// tight content bbox (from the solid B) + a little margin
let minX = W, minY = H, maxX = 0, maxY = 0;
for (let y = 0; y < H; y++) {
  for (let x = 0; x < W; x++) {
    if (bSolid(y * W + x)) {
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
}
const M = 8;
const cx0 = Math.max(0, minX - M);
const cy0 = Math.max(0, minY - M);
const cx1 = Math.min(W - 1, maxX + M);
const cy1 = Math.min(H - 1, maxY + M);
const CW = cx1 - cx0 + 1;
const CH = cy1 - cy0 + 1;

// kettlebell bbox (for the swing pivot), in cropped coords
let kMinX = W, kMinY = H, kMaxX = 0, kMaxY = 0;
for (let y = 0; y < H; y++) {
  for (let x = 0; x < W; x++) {
    if (kettlebell(y * W + x)) {
      if (x < kMinX) kMinX = x;
      if (x > kMaxX) kMaxX = x;
      if (y < kMinY) kMinY = y;
      if (y > kMaxY) kMaxY = y;
    }
  }
}
const kbCx = (kMinX + kMaxX) / 2 - cx0;
const kbTop = kMinY - cy0;
const kbH = kMaxY - kMinY;
// pivot at the grip (a bit below the very top of the handle)
const pivot = { x: Math.round(kbCx), y: Math.round(kbTop + kbH * 0.12) };
// bell centre (lower third of the kettlebell) for the impact ring
const center = { x: Math.round(kbCx), y: Math.round(kbTop + kbH * 0.64) };

// build a cropped 1-channel bitmap (black shape on white) for a predicate
function maskBuf(pred) {
  const buf = Buffer.alloc(CW * CH, 255);
  for (let y = 0; y < CH; y++) {
    for (let x = 0; x < CW; x++) {
      const i = (y + cy0) * W + (x + cx0);
      if (pred(i)) buf[y * CW + x] = 0; // black = shape
    }
  }
  return sharp(buf, { raw: { width: CW, height: CH, channels: 1 } }).png().toBuffer();
}

function traceD(pngBuffer) {
  return new Promise((resolve, reject) => {
    potrace.trace(
      pngBuffer,
      { threshold: 128, turdSize: 4, optCurve: true, optTolerance: 0.4 },
      (err, svg) => {
        if (err) return reject(err);
        // collect every d="..." (potrace emits one path; holes are sub-paths)
        const ds = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);
        resolve(ds.join(" "));
      }
    );
  });
}

const [bD, kbD] = await Promise.all([maskBuf(bSolid).then(traceD), maskBuf(kettlebell).then(traceD)]);

const out = `// AUTO-GENERATED by scripts/trace-mark.mjs from public/logo-icon.png.
// Exact vector trace of the BUILD logomark. Do not hand-edit — re-run the script.

export const MARK_W = ${CW};
export const MARK_H = ${CH};

// pendulum pivot for the splash swing (handle/grip), in viewBox coords
export const KB_PIVOT = { x: ${pivot.x}, y: ${pivot.y} };

// bell centre, for the impact ring pulse
export const KB_CENTER = { x: ${center.x}, y: ${center.y} };

// solid B silhouette (kettlebell area filled, no holes)
export const B_SOLID_PATH =
  "${bD}";

// the kettlebell: outer bell+handle with the grip as a hole. Render with
// fillRule="evenodd" so the grip reads as a hole (potrace winds it for evenodd).
export const KETTLEBELL_PATH =
  "${kbD}";
`;

writeFileSync("src/components/markPaths.ts", out);
console.log(`wrote src/components/markPaths.ts  viewBox ${CW}x${CH}  pivot ${pivot.x},${pivot.y}  Blen ${bD.length} KBlen ${kbD.length}`);
